// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// BMPPolarProjectionR
SEXP BMPPolarProjectionR(SEXP Vs, SEXP h, SEXP w, SEXP nZenithR, SEXP nAzimutR, SEXP a0R, SEXP revNum);
RcppExport SEXP cimesr_BMPPolarProjectionR(SEXP VsSEXP, SEXP hSEXP, SEXP wSEXP, SEXP nZenithRSEXP, SEXP nAzimutRSEXP, SEXP a0RSEXP, SEXP revNumSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Vs(VsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type h(hSEXP );
        Rcpp::traits::input_parameter< SEXP >::type w(wSEXP );
        Rcpp::traits::input_parameter< SEXP >::type nZenithR(nZenithRSEXP );
        Rcpp::traits::input_parameter< SEXP >::type nAzimutR(nAzimutRSEXP );
        Rcpp::traits::input_parameter< SEXP >::type a0R(a0RSEXP );
        Rcpp::traits::input_parameter< SEXP >::type revNum(revNumSEXP );
        SEXP __result = BMPPolarProjectionR(Vs, h, w, nZenithR, nAzimutR, a0R, revNum);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// opennessR
SEXP opennessR(SEXP fracR, SEXP slopeR, SEXP aspectR, SEXP imgId);
RcppExport SEXP cimesr_opennessR(SEXP fracRSEXP, SEXP slopeRSEXP, SEXP aspectRSEXP, SEXP imgIdSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type fracR(fracRSEXP );
        Rcpp::traits::input_parameter< SEXP >::type slopeR(slopeRSEXP );
        Rcpp::traits::input_parameter< SEXP >::type aspectR(aspectRSEXP );
        Rcpp::traits::input_parameter< SEXP >::type imgId(imgIdSEXP );
        SEXP __result = opennessR(fracR, slopeR, aspectR, imgId);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// thresholdR
SEXP thresholdR(SEXP Vs, SEXP Th, SEXP h, SEXP w);
RcppExport SEXP cimesr_thresholdR(SEXP VsSEXP, SEXP ThSEXP, SEXP hSEXP, SEXP wSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Vs(VsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type Th(ThSEXP );
        Rcpp::traits::input_parameter< SEXP >::type h(hSEXP );
        Rcpp::traits::input_parameter< SEXP >::type w(wSEXP );
        SEXP __result = thresholdR(Vs, Th, h, w);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
