# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BMPPolarProjectionR <- function(Vs, h, w, nZenithR, nAzimutR, a0R, revNum) {
    .Call('cimesr_BMPPolarProjectionR', PACKAGE = 'cimesr', Vs, h, w, nZenithR, nAzimutR, a0R, revNum)
}

BMPPolarGroupingR <- function(Vs, height, width, ZinfR, ZsupR, ZpasR) {
    .Call('cimesr_BMPPolarGroupingR', PACKAGE = 'cimesr', Vs, height, width, ZinfR, ZsupR, ZpasR)
}

opennessR <- function(fracR, slopeR, aspectR, imgId) {
    .Call('cimesr_opennessR', PACKAGE = 'cimesr', fracR, slopeR, aspectR, imgId)
}

thresholdR <- function(Vs, Th, h, w) {
    .Call('cimesr_thresholdR', PACKAGE = 'cimesr', Vs, Th, h, w)
}

